#!/usr/bin/env python
# -*- encoding: utf-8 -*-

KEY_SONG = "music:song:{song_id}"
KEY_LYRIC = "music:lyric:{song_id}"
TTL_MUSIC = 7200

NAME_FORMAT_TYPE_NAME = 0
NAME_FORMAT_TYPE_ARTISTS_NAME = 1
NAME_FORMAT_TYPE_NAME_ARTISTS = 2

NAME_FORMAT_TYPE_MAP = {
    NAME_FORMAT_TYPE_NAME: '{name}',
    NAME_FORMAT_TYPE_ARTISTS_NAME: '{artists} - {name}',
    NAME_FORMAT_TYPE_NAME_ARTISTS: '{name} - {artists}',
}

EXPORT_LYRIC_TYPE_ORIGIN = 0
EXPORT_LYRIC_TYPE_TRANSLATED = 1
EXPORT_LYRIC_TYPE_MIX = 2
